<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CreateIcpx>true</CreateIcpx>
    <RootNamespace>RemoteMessagePlugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="E:\Develop\community\InkCanvas.PluginSdk\InkCanvas.PluginSdk.csproj" />
  </ItemGroup>

  <Import Project="E:\Develop\community\InkCanvas.PluginSdk\InkCanvas.PluginSdk.targets" />

  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="notify-normal-new.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
