name: Build

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md', 'LICENSE' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md', 'LICENSE' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: InkCanvasForClass/community/.github/workflows/plugin-build.yml@net6
    with:
      project: RemoteMessagePlugin.csproj
      plugin_id: remotemessage.plugin
      plugin_name: RemoteMessage
      plugin_description: '远程消息，使用ICCCE的灵动通知API'
      create_release: true
      release_tag: ${{ inputs.tag || github.ref_name }}
    secrets: inherit
